package com.ifun361.musiclist.model;

import java.util.HashMap;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * 推荐分组
 * Entity mapped to table LIST_RECOMMEND_GROUPS_LIST.
 */
public class ListRecommendGroupsList {

    private Long id;
    private Integer position;
    private Integer recommendGroupId;
    private Integer status;
    private String name;
    private Integer recommendCount;
    public HashMap<Integer, RecommendsList> Recommends;

    public ListRecommendGroupsList() {
    }

    public ListRecommendGroupsList(Long id) {
        this.id = id;
    }

    public ListRecommendGroupsList(Long id, Integer position, Integer recommendGroupId, Integer status, String name, Integer recommendCount) {
        this.id = id;
        this.position = position;
        this.recommendGroupId = recommendGroupId;
        this.status = status;
        this.name = name;
        this.recommendCount = recommendCount;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getPosition() {
        return position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }

    public Integer getRecommendGroupId() {
        return recommendGroupId;
    }

    public void setRecommendGroupId(Integer recommendGroupId) {
        this.recommendGroupId = recommendGroupId;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getRecommendCount() {
        return recommendCount;
    }

    public void setRecommendCount(Integer recommendCount) {
        this.recommendCount = recommendCount;
    }

}
