package com.ifun361.musiclist.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table RECOMMENDS_LIST.
 */
public class RecommendsList {

    private Long id;
    private Integer recommendId;
    private String title;
    private String pictureFile;
    private String link;
    private Integer contentType;
    private Integer contentId;
    private Integer status;
    private Integer recommendGroupId;
    private Integer position;

    public RecommendsList() {
    }

    public RecommendsList(Long id) {
        this.id = id;
    }

    public RecommendsList(Long id, Integer recommendId, String title, String pictureFile, String link, Integer contentType, Integer contentId, Integer status, Integer recommendGroupId, Integer position) {
        this.id = id;
        this.recommendId = recommendId;
        this.title = title;
        this.pictureFile = pictureFile;
        this.link = link;
        this.contentType = contentType;
        this.contentId = contentId;
        this.status = status;
        this.recommendGroupId = recommendGroupId;
        this.position = position;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getRecommendId() {
        return recommendId;
    }

    public void setRecommendId(Integer recommendId) {
        this.recommendId = recommendId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getPictureFile() {
        return pictureFile;
    }

    public void setPictureFile(String pictureFile) {
        this.pictureFile = pictureFile;
    }

    public String getLink() {
        return link;
    }

    public void setLink(String link) {
        this.link = link;
    }

    public Integer getContentType() {
        return contentType;
    }

    public void setContentType(Integer contentType) {
        this.contentType = contentType;
    }

    public Integer getContentId() {
        return contentId;
    }

    public void setContentId(Integer contentId) {
        this.contentId = contentId;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getRecommendGroupId() {
        return recommendGroupId;
    }

    public void setRecommendGroupId(Integer recommendGroupId) {
        this.recommendGroupId = recommendGroupId;
    }

    public Integer getPosition() {
        return position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }

}
