package com.ifun361.musiclist.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;


import com.ifun361.musiclist.db.ListRecommendGroupsListDao;
import com.ifun361.musiclist.db.PlaylistsDao;
import com.ifun361.musiclist.db.RecommendsListDao;
import com.ifun361.musiclist.db.ThemesListDao;
import com.ifun361.musiclist.model.ListRecommendGroupsList;
import com.ifun361.musiclist.model.Playlists;
import com.ifun361.musiclist.model.RecommendsList;
import com.ifun361.musiclist.model.ThemesList;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig themesListDaoConfig;
    private final DaoConfig playlistsDaoConfig;
    private final DaoConfig recommendsListDaoConfig;
    private final DaoConfig listRecommendGroupsListDaoConfig;

    private final ThemesListDao themesListDao;
    private final PlaylistsDao playlistsDao;
    private final RecommendsListDao recommendsListDao;
    private final ListRecommendGroupsListDao listRecommendGroupsListDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        themesListDaoConfig = daoConfigMap.get(ThemesListDao.class).clone();
        themesListDaoConfig.initIdentityScope(type);

        playlistsDaoConfig = daoConfigMap.get(PlaylistsDao.class).clone();
        playlistsDaoConfig.initIdentityScope(type);

        recommendsListDaoConfig = daoConfigMap.get(RecommendsListDao.class).clone();
        recommendsListDaoConfig.initIdentityScope(type);

        listRecommendGroupsListDaoConfig = daoConfigMap.get(ListRecommendGroupsListDao.class).clone();
        listRecommendGroupsListDaoConfig.initIdentityScope(type);

        themesListDao = new ThemesListDao(themesListDaoConfig, this);
        playlistsDao = new PlaylistsDao(playlistsDaoConfig, this);
        recommendsListDao = new RecommendsListDao(recommendsListDaoConfig, this);
        listRecommendGroupsListDao = new ListRecommendGroupsListDao(listRecommendGroupsListDaoConfig, this);

        registerDao(ThemesList.class, themesListDao);
        registerDao(Playlists.class, playlistsDao);
        registerDao(RecommendsList.class, recommendsListDao);
        registerDao(ListRecommendGroupsList.class, listRecommendGroupsListDao);
    }
    
    public void clear() {
        themesListDaoConfig.getIdentityScope().clear();
        playlistsDaoConfig.getIdentityScope().clear();
        recommendsListDaoConfig.getIdentityScope().clear();
        listRecommendGroupsListDaoConfig.getIdentityScope().clear();
    }

    public ThemesListDao getThemesListDao() {
        return themesListDao;
    }

    public PlaylistsDao getPlaylistsDao() {
        return playlistsDao;
    }

    public RecommendsListDao getRecommendsListDao() {
        return recommendsListDao;
    }

    public ListRecommendGroupsListDao getListRecommendGroupsListDao() {
        return listRecommendGroupsListDao;
    }

}
