package com.ifun361.musiclist.model;

import java.util.HashMap;



// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * 音乐列表
 * Entity mapped to table PLAYLISTS.
 */
public class Playlists extends BaseModel{

    private Long id;
    private Integer position;
    private Integer playlistId;
    private Integer editorId;
    private Integer themeId;
    private Long publishTime;
    private Integer backgrounds;
    private String name;
    private Integer playitemCount;
    private String lead;
    public HashMap<Integer, Playitems> playitems;
    //private Playitems playitems;
    private Integer taste;
    private Integer playitemDuration;

    /*public Playitems getPlayitems() {
		return playitems;
	}

	public void setPlayitems(Playitems playitems) {
		this.playitems = playitems;
	}
*/
	public Playlists() {
    }

    public Playlists(Long id) {
        this.id = id;
    }

    public Playlists(Long id, Integer position, Integer playlistId, Integer editorId, Integer themeId, Long publishTime, Integer backgrounds, String name, Integer playitemCount, String lead, Integer taste, Integer playitemDuration) {
        this.id = id;
        this.position = position;
        this.playlistId = playlistId;
        this.editorId = editorId;
        this.themeId = themeId;
        this.publishTime = publishTime;
        this.backgrounds = backgrounds;
        this.name = name;
        this.playitemCount = playitemCount;
        this.lead = lead;
        this.taste = taste;
        this.playitemDuration = playitemDuration;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getPosition() {
        return position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }

    public Integer getPlaylistId() {
        return playlistId;
    }

    public void setPlaylistId(Integer playlistId) {
        this.playlistId = playlistId;
    }

    public Integer getEditorId() {
        return editorId;
    }

    public void setEditorId(Integer editorId) {
        this.editorId = editorId;
    }

    public Integer getThemeId() {
        return themeId;
    }

    public void setThemeId(Integer themeId) {
        this.themeId = themeId;
    }

    public Long getPublishTime() {
        return publishTime;
    }

    public void setPublishTime(Long publishTime) {
        this.publishTime = publishTime;
    }

    public Integer getBackgrounds() {
        return backgrounds;
    }

    public void setBackgrounds(Integer backgrounds) {
        this.backgrounds = backgrounds;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getPlayitemCount() {
        return playitemCount;
    }

    public void setPlayitemCount(Integer playitemCount) {
        this.playitemCount = playitemCount;
    }

    public String getLead() {
        return lead;
    }

    public void setLead(String lead) {
        this.lead = lead;
    }

    public Integer getTaste() {
        return taste;
    }

    public void setTaste(Integer taste) {
        this.taste = taste;
    }

    public Integer getPlayitemDuration() {
        return playitemDuration;
    }

    public void setPlayitemDuration(Integer playitemDuration) {
        this.playitemDuration = playitemDuration;
    }

}
